"""empty message

Revision ID: 0d0d1c42a2c9
Revises: 1da1b8bcb1a5
Create Date: 2019-05-28 15:16:19.724008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0d1c42a2c9'
down_revision = '1da1b8bcb1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
