"""empty message

Revision ID: 47cf8a56d9dc
Revises: f26ad068390a
Create Date: 2019-05-28 16:28:04.972563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cf8a56d9dc'
down_revision = 'f26ad068390a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(length=40), nullable=True))
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
