"""Add git parameters to model

Revision ID: ebbfb7d55f62
Revises: 75933cf6bdb9
Create Date: 2019-04-01 14:50:29.492904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ebbfb7d55f62"
down_revision = "75933cf6bdb9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("git_active_branch", sa.String(), nullable=True))
    op.add_column("models", sa.Column("git_commit_hash", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "git_commit_hash")
    op.drop_column("models", "git_active_branch")
    # ### end Alembic commands ###
